services:
  # --- CƠ SỞ DỮ LIỆU ---
  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    #ports:
    #  - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "Putin@140223"
      MYSQL_DATABASE: "customer_ebank"
    volumes:
      - mysql_data:/var/lib/mysql
      # Ánh xạ thư mục chứa file init.sql để tự tạo nhiều database
      - ./init-db:/docker-entrypoint-initdb.d
    networks:
      - ebank-network
    deploy:
      resources:
        limits:
          memory: 400M

  # --- EUREKA SERVER (Discovery) ---
  discovery-service:
    build: ./discovery-service
    container_name: discovery-service
    #ports:
    #  - "8761:8761"
    networks:
      - ebank-network
    deploy:
      resources:
        limits:
          memory: 300M

  # --- API GATEWAY (Cửa ngõ hệ thống) ---
  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - discovery-service
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka/
    networks:
      - ebank-network
    deploy:
      resources:
        limits:
          memory: 350M

  # --- AUTH SERVICE ---
  auth-service:
    build: ./auth-service
    container_name: auth-service
    depends_on:
      - discovery-service
      - mysql-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/auth_ebank
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka/
    networks:
      - ebank-network
    deploy:
      resources:
        limits:
          memory: 300M

  # --- CUSTOMER SERVICE ---
  customer-service:
    build: ./customer-service
    container_name: customer-service
    depends_on:
      - discovery-service
      - mysql-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/customer_ebank
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka/
      - EUREKA_INSTANCE_IP_ADDRESS=customer-service
    networks:
      - ebank-network
    deploy:
      resources:
        limits:
          memory: 350M

  # --- BANK ADMIN SERVICE ---
  bankadmin-service:
    build: ./bankadmin-service
    container_name: bankadmin-service
    depends_on:
      - discovery-service
      - mysql-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/bankadmin_ebank
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka/
      - EUREKA_INSTANCE_IP_ADDRESS=bankadmin-service
    networks:
      - ebank-network
    deploy:
      resources:
        limits:
          memory: 350M

  onboard-service:
    build: ./onboard-service
    container_name: onboard-service
    depends_on:
      - discovery-service
      - mysql-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/onboard_ebank
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka/
      - EUREKA_INSTANCE_IP_ADDRESS=onboard-service
    networks:
      - ebank-network
    deploy:
      resources:
        limits:
          memory: 350M

  file-service:
    build: ./file-service
    container_name: file-service
    depends_on:
      - discovery-service
      - mysql-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/file_ebank
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka/
      - EUREKA_INSTANCE_IP_ADDRESS=file-service
    networks:
      - ebank-network
    deploy:
      resources:
        limits:
          memory: 350M

  fundtransfer-service:
    build: ./fundtransfer-service
    container_name: fundtransfer-service
    depends_on:
      - discovery-service
      - mysql-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/fundtransfer-service
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka/
      - EUREKA_INSTANCE_IP_ADDRESS=fundtransfer-service
    networks:
      - ebank-network
    deploy:
      resources:
        limits:
          memory: 350M
networks:
  ebank-network:
    driver: bridge

volumes:
  mysql_data: