server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
          predicates:
            - name: Path
              args:
                pattern: "'/api-gateway/' + serviceId + '/**'"
          filters:
            - name: StripPrefix
              args:
                parts: 1

eureka:
  client:
    service-url:
      defaultZone: http://admin:Ebank_2026@discovery-service:8761/eureka/

jwt:
  secret: K7vN3pL9xM2qR5wT8jY4bC6zF1gH0dJ9sK5mN2bP

api:
  gateway:
    open-endpoints: >
      /api-gateway/auth-service/auth/login,
      /api-gateway/onboard-service/v1/onboard,
      /api-gateway/eureka,
      /api-gateway/file-service/v1/file/upload