server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: false # Nhìn vào Eureka để tự động tạo đường dẫn
          lower-case-service-id: true # Ép tên service trên URL thành chữ thường (ví dụ: /auth-service)
      # 2. CẤU HÌNH CORS (Cho phép Frontend gọi API)
      globalcors:
        cors-configurations:
          '[/**]': # Áp dụng cho mọi đường dẫn API
            allowedOrigins: "*" # Cho phép mọi Frontend gọi vào (hoặc thay bằng URL FE của bạn như http://localhost:3000)
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
      routes:
        - id: customer-service
          uri: lb://CUSTOMER-SERVICE
          predicates:
            - Path=/customer-service/v1/customer/**
        - id: onboard-service
          uri: lb://onboard-service
          predicates:
              - Path=/onboard-service/**
        - id: file-service
          uri: lb://file-service
          predicates:
              - Path=/file-service/v1/file/**
        - id: bankadmin-service
          uri: lb://bankadmin-service
          predicates:
              - Path=/bankadmin-service/**
        - id: fundtransfer-service
          uri: lb://fundtransfer-service
          predicates:
            - Path=/fundtransfer-service/**
        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/auth-service/v1/**

eureka:
  client:
    service-url:
      defaultZone: http://admin:Ebank_2026@discovery-service:8761/eureka/

jwt:
  secret: K7vN3pL9xM2qR5wT8jY4bC6zF1gH0dJ9sK5mN2bP

api:
  gateway:
    open-endpoints: /auth-service/v1/auth/login, /auth-service/v1/auth/register, /onboard-service/, /eureka